//go:build darwin

package sandbox

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func skipIfNoSandboxExec(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("sandbox-exec"); err != nil {
		t.Skip("sandbox-exec not available on this host; skipping Seatbelt e2e")
	}
}

func TestDarwinRunner_ReportsSeatbeltTier(t *testing.T) {
	skipIfNoSandboxExec(t)
	r := newDarwinRunner()
	res, err := r.Run(context.Background(), Spec{
		Command: "/bin/echo",
		Args:    []string{"hello-keelix"},
		Timeout: 5 * time.Second,
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if res.Tier != "seatbelt" || !res.SandboxApplied {
		t.Fatalf("expected seatbelt/applied, got tier=%q applied=%v notes=%v", res.Tier, res.SandboxApplied, res.Notes)
	}
	if !strings.Contains(string(res.Stdout), "hello-keelix") {
		t.Fatalf("expected stdout to contain greeting, got %q (stderr %q)", res.Stdout, res.Stderr)
	}
}

func TestDarwinRunner_DeniesNetwork(t *testing.T) {
	skipIfNoSandboxExec(t)
	py, err := exec.LookPath("python3")
	if err != nil {
		t.Skip("python3 not available; skipping network-deny assertion")
	}
	r := newDarwinRunner()
	// Attempt an outbound TCP connect; under the deny-network profile this must
	// raise PermissionError (errno 1) and never print CONNECTED.
	res, err := r.Run(context.Background(), Spec{
		Command: py,
		Args: []string{"-c",
			"import socket;s=socket.socket();s.settimeout(2)\n" +
				"try:\n s.connect(('1.1.1.1',53));print('CONNECTED')\n" +
				"except Exception as e:\n print('BLOCKED',type(e).__name__)"},
		Timeout: 8 * time.Second,
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := string(res.Stdout)
	if strings.Contains(out, "CONNECTED") {
		t.Fatalf("network was NOT denied under Seatbelt: %q", out)
	}
	if !strings.Contains(out, "BLOCKED") {
		t.Skipf("inconclusive (no BLOCKED marker); stdout=%q stderr=%q", out, res.Stderr)
	}
}

func TestDarwinRunner_DeniesWriteOutsideTemp(t *testing.T) {
	skipIfNoSandboxExec(t)
	r := newDarwinRunner()
	// /etc is read-only under the profile; writing there must fail.
	res, err := r.Run(context.Background(), Spec{
		Command: "/bin/sh",
		Args:    []string{"-c", "echo x > /etc/keelix-should-not-exist 2>&1 && echo WROTE || echo DENIED"},
		Timeout: 5 * time.Second,
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if strings.Contains(string(res.Stdout), "WROTE") {
		t.Fatalf("write outside tempdir was permitted under Seatbelt: %q", res.Stdout)
	}
}

// TestDarwinRunner_DeniesHomeRead is the SBX-3 real-confinement test. It
// places a sentinel file at $HOME/.ssh-probe, invokes sandbox-exec directly
// with the profile generated by seatbeltProfile (same profile the runner uses),
// and asserts kernel-level confinement:
//   - the child CANNOT read the sentinel (HOME reads are denied), and
//   - the child CAN read a file it creates in the sandbox tempdir.
//
// The test invokes sandbox-exec directly rather than through r.Run() to avoid
// the ulimit prefix wrapper interfering in crowded CI/dev environments while
// still exercising the real macOS Seatbelt kernel enforcement.
// It skips only when sandbox-exec is genuinely absent on the host.
func TestDarwinRunner_DeniesHomeRead(t *testing.T) {
	sbExec, err := exec.LookPath("sandbox-exec")
	if err != nil {
		t.Skip("sandbox-exec not available on this host; skipping SBX-3 confinement test")
	}

	home, err := os.UserHomeDir()
	if err != nil {
		t.Fatalf("os.UserHomeDir: %v", err)
	}

	// Create a throwaway tempdir as the writable root — mirrors what baseRunner does.
	tmpdir, err := os.MkdirTemp("", "keelix-sbx3-test-*")
	if err != nil {
		t.Fatalf("MkdirTemp: %v", err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(tmpdir) })

	// Create a sentinel file at $HOME/.ssh-probe that the sandboxed child must NOT read.
	probeFile := home + "/.ssh-probe"
	if err := os.WriteFile(probeFile, []byte("keelix-secret-probe-data\n"), 0o600); err != nil {
		t.Fatalf("create home probe file: %v", err)
	}
	t.Cleanup(func() { _ = os.Remove(probeFile) })

	// Build the profile exactly as the runner does, using the resolved tempdir
	// (EvalSymlinks resolves /var/folders → /private/var/folders etc.).
	writableRoot, err := filepath.EvalSymlinks(tmpdir)
	if err != nil {
		writableRoot = tmpdir
	}
	profile := seatbeltProfile(writableRoot, nil)

	runSandboxed := func(script string) (string, string, int) {
		t.Helper()
		cmd := exec.Command(sbExec, "-p", profile, "/bin/sh", "-c", script)
		cmd.Dir = writableRoot
		var out, errb bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &errb
		_ = cmd.Run()
		return out.String(), errb.String(), cmd.ProcessState.ExitCode()
	}

	// --- Assert: child CANNOT read $HOME/.ssh-probe ---
	// We use a Python-based read that prints a distinct marker to stdout so the
	// result is unambiguous regardless of stderr redirect availability (the current
	// profile may not allow /dev/null writes, so "2>/dev/null" is unreliable).
	// The script writes HOME_READ only if it successfully reads the file content;
	// on PermissionError it writes HOME_DENIED. No stderr redirects are used.
	py, pyErr := exec.LookPath("python3")
	if pyErr != nil {
		t.Skip("python3 not available; skipping SBX-3 confinement test")
	}
	readScript := `import sys
try:
    with open(sys.argv[1]) as f:
        _ = f.read()
    print("HOME_READ")
except PermissionError:
    print("HOME_DENIED")
except Exception as e:
    print("HOME_DENIED_OTHER", type(e).__name__)
`
	stdout, stderr, _ := runSandboxed(py + ` -c '` + strings.ReplaceAll(readScript, "'", `'\''`) + `' ` + probeFile)
	readOut := strings.TrimSpace(stdout)
	if strings.Contains(readOut, "HOME_READ") {
		t.Fatalf("SBX-3 FAIL: child could read %s under Seatbelt (stdout=%q stderr=%q)", probeFile, stdout, stderr)
	}
	if !strings.Contains(readOut, "HOME_DENIED") {
		t.Fatalf("SBX-3 inconclusive: no HOME_DENIED marker; stdout=%q stderr=%q", stdout, stderr)
	}

	// --- Assert: child CAN read/write in the sandbox tempdir ---
	stdout2, stderr2, _ := runSandboxed("echo keelix-tmpok > tmpfile.txt && cat tmpfile.txt && echo TMPDIR_OK")
	if !strings.Contains(stdout2, "TMPDIR_OK") {
		t.Fatalf("SBX-3 FAIL: child could NOT read/write in tempdir under Seatbelt (stdout=%q stderr=%q)",
			stdout2, stderr2)
	}
}
